name: yolo11
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - opencv-python
  - pillow
  - pyarrow
  - pyyaml
  - psutil
  - sympy
  - click
  - jinja2
  - packaging
  - tqdm
  - filelock
  - fonttools
  - kiwisolver
  - contourpy
  - cycler
  - python-dateutil
  - pytz
  - six
  - networkx
  - mpmath
  - jsonschema
  - jsonschema-specifications
  - referencing
  - attrs
  - annotated-types
  - pydantic
  - pydantic-core
  - typing-extensions
  - typing-inspection
  - platformdirs
  - urllib3
  - requests
  - certifi
  - charset-normalizer
  - idna
  - zlib
  - bzip2
  - lzma
  - libffi
  - openssl
  - readline
  - tk
  - ncurses
  - libuuid
  - libxcrypt
  - libsqlite
  - ca-certificates
  - libnsl
  - pip:
      - torch==2.7.1
      - torchvision==0.22.1
      - ultralytics==8.3.160
      - ultralytics-thop==2.0.14
      - ray==2.47.1
      - tensorboardx==2.6.4
      - wandb==0.20.1
      - protobuf==6.31.1
      - smmap==5.0.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - setproctitle==1.3.6
